# Generated by Django 5.0.14 on 2025-05-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('num_cnss', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('situation_familiale', models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf(ve)')], max_length=1)),
                ('enfants', models.IntegerField(default=0)),
                ('num_cnss', models.CharField(max_length=20)),
                ('rib', models.CharField(max_length=24)),
                ('date_embauche', models.DateField()),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage')], max_length=5)),
                ('qualification', models.CharField(max_length=100)),
                ('salaire_base', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_paie_app.societe')),
            ],
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('jours_travailles', models.IntegerField()),
                ('salaire_base', models.DecimalField(decimal_places=3, max_digits=10)),
                ('prime_presence', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('indemnite_transport', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('prime_non_concurrence', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cotisation_cnss', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('irpp', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cotisation_solidarite', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('salaire_brut', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salaire_imposable', models.DecimalField(decimal_places=3, max_digits=10)),
                ('salaire_net', models.DecimalField(decimal_places=3, max_digits=10)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('PAYE', 'Payé')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_paie_app.employe')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_paie_app.societe')),
            ],
            options={
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
    ]
